import { Subject } from "@/types";

export const SUBJECTS: Subject[] = [
  {
    id: "deutsch", label: "Deutsch", color: "#7EC8E3",
    grades: [
      { grade: 5, topics: [{ id: "satzglieder", label: "Satzglieder & Satzarten" }, { id: "erzaehlen", label: "Erzählen & Beschreiben" }, { id: "rechtschreibung", label: "Rechtschreibung: Groß- und Kleinschreibung" }, { id: "maerchen", label: "Märchen & Fabeln lesen" }] },
      { grade: 6, topics: [{ id: "wortarten", label: "Wortarten wiederholen" }, { id: "kurzgeschichten", label: "Kurzgeschichten lesen & analysieren" }, { id: "argumentation-einfach", label: "Argumentation einfach" }, { id: "briefe", label: "Briefe & E-Mails schreiben" }] },
      { grade: 7, topics: [{ id: "eroerterung", label: "Erörterung vorbereiten" }, { id: "lyrik", label: "Lyrische Texte verstehen" }, { id: "satzverbindungen", label: "Grammatik: Satzverbindungen" }, { id: "jugendbuch", label: "Jugendbuch analysieren" }] },
      { grade: 8, topics: [{ id: "lyrik-analyse", label: "Analyse lyrischer Texte" }, { id: "argumentation-formal", label: "Formale Argumentation" }, { id: "sprachreflexion", label: "Sprachreflexion" }, { id: "dramen", label: "Dramen lesen" }] },
      { grade: 9, topics: [{ id: "drama-analyse", label: "Dramenanalyse" }, { id: "argumentation-komplex", label: "Komplexe Argumentation" }, { id: "sprachgeschichte", label: "Sprachgeschichte & Variation" }, { id: "kurzprosa", label: "Kurzprosa analysieren" }] },
      { grade: 10, topics: [{ id: "epochen", label: "Literarische Epochen" }, { id: "textanalyse", label: "Textanalyse vertieft" }, { id: "sprachkritik", label: "Sprachkritik & Medien" }, { id: "oberstufe-vorbereitung", label: "Vorbereitung Oberstufe" }] },
      { grade: 11, topics: [{ id: "einfuehrungsphase", label: "Einführungsphase: Textanalyse & Interpretation" }, { id: "erzaehlprosa", label: "Erzählprosa: Romane der Moderne" }, { id: "sprachliche-mittel", label: "Sprachliche Mittel & ihre Wirkung" }, { id: "eroerterung-os", label: "Erörterung & Argumentationsstrukturen" }] },
      { grade: 12, topics: [{ id: "dramenanalyse-os", label: "Dramenanalyse: klassische & moderne Texte" }, { id: "lyrik-epochen", label: "Lyrik: Epochen im Vergleich" }, { id: "materialgestuetzt", label: "Materialgestütztes Schreiben" }, { id: "sprachgeschichte-os", label: "Sprachgeschichte & Sprachkritik" }] },
      { grade: 13, topics: [{ id: "abitur-prosa", label: "Abitur: Textanalyse Prosa" }, { id: "abitur-lyrik", label: "Abitur: Lyrikvergleich" }, { id: "abitur-eroerterung", label: "Abitur: Erörterung mit Materialien" }, { id: "medialitaet", label: "Sprachreflexion & Medialität" }] },
    ]
  },
  {
    id: "englisch", label: "Englisch", color: "#85C7A0",
    grades: [
      { grade: 5, topics: [{ id: "greeting", label: "Greeting & Introducing" }, { id: "school-vocab", label: "School vocabulary" }, { id: "simple-present", label: "Simple present" }, { id: "numbers", label: "Numbers & colours" }] },
      { grade: 6, topics: [{ id: "family", label: "Family & Friends" }, { id: "present-prog", label: "Present progressive" }, { id: "reading", label: "Reading short texts" }, { id: "hobbies", label: "Talking about hobbies" }] },
      { grade: 7, topics: [{ id: "conditional", label: "Conditional I" }, { id: "media", label: "Media & Technology" }, { id: "images", label: "Describing images" }, { id: "letter", label: "Letter & email writing" }] },
      { grade: 8, topics: [{ id: "passive", label: "Passive voice basics" }, { id: "environment", label: "Environmental issues" }, { id: "text-analysis", label: "Text analysis intro" }, { id: "opinions", label: "Discussing opinions" }] },
      { grade: 9, topics: [{ id: "grammar-review", label: "Advanced grammar review" }, { id: "current-affairs", label: "Current affairs" }, { id: "essay", label: "Essay writing" }, { id: "short-story", label: "Short story analysis" }] },
      { grade: 10, topics: [{ id: "literature", label: "Literature analysis" }, { id: "debate", label: "Debate & Discussion" }, { id: "academic", label: "Academic writing" }, { id: "global", label: "Global challenges" }] },
      { grade: 11, topics: [{ id: "literary-analysis", label: "Introduction to literary analysis" }, { id: "american-dream", label: "American Dream & Identity" }, { id: "non-fiction", label: "Non-fiction & media texts" }, { id: "comment", label: "Writing: comment & analysis" }] },
      { grade: 12, topics: [{ id: "post-colonial", label: "Post-colonial literature" }, { id: "globalisation", label: "Globalisation & politics" }, { id: "genre-compare", label: "Comparing texts across genres" }, { id: "language-power", label: "Language & power" }] },
      { grade: 13, topics: [{ id: "abitur-essay", label: "Abitur: analytical essay" }, { id: "abitur-mediation", label: "Abitur: mediation" }, { id: "abitur-compare", label: "Abitur: text comparison" }, { id: "contemporary", label: "Contemporary issues in English-speaking world" }] },
    ]
  },
  {
    id: "mathematik", label: "Mathematik", color: "#F4A261",
    grades: [
      { grade: 5, topics: [{ id: "nat-zahlen", label: "Natürliche Zahlen" }, { id: "geo-grundformen", label: "Geometrie: Grundformen" }, { id: "bruch-intro", label: "Bruchrechnung Einführung" }, { id: "groessen", label: "Größen & Einheiten" }] },
      { grade: 6, topics: [{ id: "brueche", label: "Brüche & Dezimalzahlen" }, { id: "flaechen", label: "Flächen & Umfang" }, { id: "neg-zahlen", label: "Negative Zahlen" }, { id: "proportionen", label: "Verhältnisse & Proportionen" }] },
      { grade: 7, topics: [{ id: "terme", label: "Terme & Gleichungen" }, { id: "prozent", label: "Prozentrechnung" }, { id: "dreiecke", label: "Dreiecke & Vierecke" }, { id: "zuordnungen", label: "Zuordnungen" }] },
      { grade: 8, topics: [{ id: "lin-funktionen", label: "Lineare Funktionen" }, { id: "gleichungssysteme", label: "Gleichungssysteme" }, { id: "statistik", label: "Statistik Grundlagen" }, { id: "pythagoras", label: "Pythagoras" }] },
      { grade: 9, topics: [{ id: "quad-gleichungen", label: "Quadratische Gleichungen" }, { id: "trigonometrie", label: "Trigonometrie" }, { id: "stochastik", label: "Stochastik" }, { id: "aehnlichkeit", label: "Ähnlichkeit & Strahlensätze" }] },
      { grade: 10, topics: [{ id: "diff-intro", label: "Differentialrechnung Einführung" }, { id: "vektoren", label: "Vektoren" }, { id: "analytische-geo", label: "Analytische Geometrie" }, { id: "integral-intro", label: "Integralrechnung Einführung" }] },
      { grade: 11, topics: [{ id: "diff-vertieft", label: "Differentialrechnung vertieft" }, { id: "kurvendiskussion", label: "Kurvendiskussion" }, { id: "integral-vertieft", label: "Integralrechnung vertieft" }, { id: "binomial", label: "Stochastik: Binomialverteilung" }] },
      { grade: 12, topics: [{ id: "geraden-ebenen", label: "Analytische Geometrie: Geraden & Ebenen" }, { id: "normalverteilung", label: "Normalverteilung & Hypothesentests" }, { id: "log-exp", label: "Logarithmus & Exponentialfunktionen" }, { id: "vektoren-vertieft", label: "Vektorrechnung vertieft" }] },
      { grade: 13, topics: [{ id: "abitur-analysis", label: "Abitur: Analysis" }, { id: "abitur-geo", label: "Abitur: Analytische Geometrie" }, { id: "abitur-stochastik", label: "Abitur: Stochastik" }, { id: "abitur-ueben", label: "Abituraufgaben üben" }] },
    ]
  },
  {
    id: "physik", label: "Physik", color: "#B39DDB",
    grades: [
      { grade: 5, topics: [{ id: "koerper-stoffe", label: "Körper & Stoffe" }, { id: "waerme", label: "Wärme & Temperatur" }, { id: "schall-licht", label: "Schall & Licht Einführung" }] },
      { grade: 6, topics: [{ id: "strom", label: "Elektrischer Strom Grundlagen" }, { id: "magnetismus", label: "Magnetismus" }, { id: "kraefte", label: "Kräfte im Alltag" }] },
      { grade: 7, topics: [{ id: "bewegung", label: "Geschwindigkeit & Bewegung" }, { id: "druck", label: "Druck in Flüssigkeiten" }, { id: "optik", label: "Optik: Reflexion & Brechung" }] },
      { grade: 8, topics: [{ id: "energie", label: "Energie & Energieumwandlung" }, { id: "schaltkreise", label: "Elektrische Schaltkreise" }, { id: "arbeit-leistung", label: "Mechanische Arbeit & Leistung" }] },
      { grade: 9, topics: [{ id: "kernphysik", label: "Kernphysik Grundlagen" }, { id: "elektromagnetismus", label: "Elektromagnetismus" }, { id: "wellen", label: "Wellen & Schwingungen" }] },
      { grade: 10, topics: [{ id: "relativitaet", label: "Relativitätstheorie Einführung" }, { id: "quantenmechanik", label: "Quantenmechanik Grundlagen" }, { id: "astrophysik", label: "Astrophysik" }] },
      { grade: 11, topics: [{ id: "newton", label: "Mechanik vertieft: Newton & Impuls" }, { id: "felder", label: "Elektrisches & magnetisches Feld" }, { id: "schwingungen-vertieft", label: "Schwingungen & Wellen vertieft" }] },
      { grade: 12, topics: [{ id: "quantenphysik", label: "Quantenphysik vertieft" }, { id: "atomphysik", label: "Atomphysik & Spektren" }, { id: "kernphysik-vertieft", label: "Kern- & Teilchenphysik" }, { id: "spezielle-rel", label: "Spezielle Relativitätstheorie" }] },
      { grade: 13, topics: [{ id: "abitur-mechanik", label: "Abitur: Mechanik" }, { id: "abitur-elektro", label: "Abitur: Elektrodynamik" }, { id: "abitur-quanten", label: "Abitur: Quantenphysik" }] },
    ]
  },
  {
    id: "chemie", label: "Chemie", color: "#EF9A9A",
    grades: [
      { grade: 7, topics: [{ id: "stoffe", label: "Stoffe & Stoffeigenschaften" }, { id: "teilchenmodell", label: "Teilchenmodell" }, { id: "trennverfahren", label: "Trennverfahren" }] },
      { grade: 8, topics: [{ id: "atombau", label: "Atombau Grundlagen" }, { id: "reaktionen", label: "Chemische Reaktionen" }, { id: "oxidation", label: "Oxidation & Reduktion" }] },
      { grade: 9, topics: [{ id: "pse", label: "Periodensystem" }, { id: "ionenbindung", label: "Ionenbindung" }, { id: "saeuren-basen", label: "Säuren & Basen" }] },
      { grade: 10, topics: [{ id: "organik-intro", label: "Organische Chemie Einführung" }, { id: "kunststoffe", label: "Kunststoffe" }, { id: "elektrochemie", label: "Elektrochemie" }] },
      { grade: 11, topics: [{ id: "kinetik", label: "Reaktionskinetik" }, { id: "gleichgewicht", label: "Chemisches Gleichgewicht" }, { id: "organik-vertieft", label: "Organische Stoffklassen vertieft" }] },
      { grade: 12, topics: [{ id: "elektrochemie-vertieft", label: "Elektrochemie vertieft: Galvanische Elemente" }, { id: "saeure-base-gw", label: "Säure-Base-Gleichgewichte" }, { id: "naturstoffe", label: "Naturstoffe: Kohlenhydrate & Proteine" }] },
      { grade: 13, topics: [{ id: "abitur-organik", label: "Abitur: Organische Chemie" }, { id: "abitur-elektrochemie", label: "Abitur: Elektrochemie" }, { id: "abitur-kinetik", label: "Abitur: Reaktionskinetik & Gleichgewicht" }] },
    ]
  },
  {
    id: "biologie", label: "Biologie", color: "#80CBC4",
    grades: [
      { grade: 5, topics: [{ id: "zelle", label: "Zelle Grundlagen" }, { id: "photosynthese", label: "Pflanzen & Photosynthese" }, { id: "oekosystem", label: "Tiere im Ökosystem" }] },
      { grade: 6, topics: [{ id: "verdauung", label: "Körperfunktionen: Verdauung" }, { id: "fortpflanzung", label: "Fortpflanzung bei Tieren" }, { id: "wald", label: "Ökosystem Wald" }] },
      { grade: 7, topics: [{ id: "genetik-intro", label: "Genetik Einführung" }, { id: "evolution-intro", label: "Evolution Grundlagen" }, { id: "gewaesser", label: "Ökosystem Gewässer" }] },
      { grade: 8, topics: [{ id: "nervensystem", label: "Nervensystem" }, { id: "hormonsystem", label: "Hormonsystem" }, { id: "verhalten", label: "Verhaltensbiologie" }] },
      { grade: 9, topics: [{ id: "humangenetik", label: "Humangenetik" }, { id: "immunsystem", label: "Immunsystem" }, { id: "stoffwechsel", label: "Stoffwechsel vertieft" }] },
      { grade: 10, topics: [{ id: "klimawandel", label: "Ökologie & Klimawandel" }, { id: "biotechnologie", label: "Biotechnologie Grundlagen" }, { id: "evolution-vertieft", label: "Evolution vertieft" }] },
      { grade: 11, topics: [{ id: "zellbiologie", label: "Zellbiologie vertieft: Membranen & Transport" }, { id: "enzymatik", label: "Enzymatik & Stoffwechselregulation" }, { id: "genregulation", label: "Genetik: Genregulation" }] },
      { grade: 12, topics: [{ id: "neurobiologie", label: "Neurobiologie vertieft" }, { id: "immunbiologie", label: "Immunbiologie & Impfung" }, { id: "populationsdynamik", label: "Ökologie: Populationsdynamik" }] },
      { grade: 13, topics: [{ id: "abitur-genetik", label: "Abitur: Genetik & Molekularbiologie" }, { id: "abitur-neuro", label: "Abitur: Neurobiologie" }, { id: "abitur-oekologie", label: "Abitur: Ökologie & Evolution" }] },
    ]
  },
  {
    id: "geschichte", label: "Geschichte", color: "#FFCC80",
    grades: [
      { grade: 5, topics: [{ id: "antike", label: "Frühgeschichte & Antike" }, { id: "aegypten", label: "Das alte Ägypten" }, { id: "griechenland", label: "Griechenland & Demokratie" }] },
      { grade: 6, topics: [{ id: "roemisches-reich", label: "Das Römische Reich" }, { id: "mittelalter", label: "Mittelalter Einführung" }, { id: "kirche", label: "Kirche & Gesellschaft im MA" }] },
      { grade: 7, topics: [{ id: "renaissance", label: "Renaissance & Reformation" }, { id: "entdeckungen", label: "Entdeckungszeitalter" }, { id: "absolutismus", label: "Absolutismus" }] },
      { grade: 8, topics: [{ id: "franz-revolution", label: "Französische Revolution" }, { id: "industrialisierung", label: "Industrialisierung" }, { id: "nationalismus", label: "Nationalismus & Imperialismus" }] },
      { grade: 9, topics: [{ id: "wwi", label: "Erster Weltkrieg" }, { id: "weimar", label: "Weimarer Republik" }, { id: "ns", label: "Nationalsozialismus & Holocaust" }] },
      { grade: 10, topics: [{ id: "wwii", label: "Zweiter Weltkrieg" }, { id: "kalter-krieg", label: "Kalter Krieg" }, { id: "wiedervereinigung", label: "Deutsche Teilung & Wiedervereinigung" }] },
      { grade: 11, topics: [{ id: "geschichtstheorie", label: "Geschichtstheorie & Quellenarbeit" }, { id: "revolutionen", label: "Revolutionen im Vergleich" }, { id: "kolonialismus", label: "Imperialismus & Kolonialismus vertieft" }] },
      { grade: 12, topics: [{ id: "ns-gesellschaft", label: "NS-Herrschaft & Gesellschaft vertieft" }, { id: "internationale-beziehungen", label: "Internationale Beziehungen im 20. Jh." }, { id: "deutschland-nachkrieg", label: "Deutschland nach 1945: Demokratie & Diktatur im Vergleich" }] },
      { grade: 13, topics: [{ id: "abitur-ns", label: "Abitur: NS-Zeit & Holocaust" }, { id: "abitur-kalter-krieg", label: "Abitur: Kalter Krieg & Entspannungspolitik" }, { id: "abitur-demokratie", label: "Abitur: Demokratie & ihre Gefährdungen" }, { id: "erinnerungskultur", label: "Erinnerungskultur & Geschichtspolitik" }] },
    ]
  },
  {
    id: "erdkunde", label: "Erdkunde", color: "#A5D6A7",
    grades: [
      { grade: 5, topics: [{ id: "orientierung", label: "Orientierung auf der Erde" }, { id: "klimazonen", label: "Klimazonen Überblick" }, { id: "wueste", label: "Leben in der Wüste" }] },
      { grade: 6, topics: [{ id: "europa", label: "Europa – Räume & Strukturen" }, { id: "landwirtschaft", label: "Landwirtschaft & Ernährung" }, { id: "bevoelkerung", label: "Bevölkerungsentwicklung" }] },
      { grade: 7, topics: [{ id: "globalisierung", label: "Entwicklungsländer & Globalisierung" }, { id: "naturkatastrophen", label: "Naturkatastrophen" }, { id: "regenwald", label: "Regenwald & Ökosysteme" }] },
      { grade: 8, topics: [{ id: "wirtschaftsraeume", label: "Wirtschaftsräume weltweit" }, { id: "staedte", label: "Verstädterung" }, { id: "energie", label: "Energie & Rohstoffe" }] },
      { grade: 9, topics: [{ id: "geopolitik", label: "Geopolitik & Konflikte" }, { id: "klimawandel-geo", label: "Klimawandel & Folgen" }, { id: "migration", label: "Migration & Flucht" }] },
      { grade: 10, topics: [{ id: "nachhaltigkeit", label: "Nachhaltige Entwicklung" }, { id: "ungleichheiten", label: "Globale Ungleichheiten" }, { id: "digitalisierung", label: "Geografie & Digitalisierung" }] },
      { grade: 11, topics: [{ id: "megastaedte", label: "Stadtentwicklung & Megastädte" }, { id: "agrarsysteme", label: "Globale Agrarsysteme" }, { id: "gis", label: "Raumanalyse & GIS" }] },
      { grade: 12, topics: [{ id: "klimawandel-os", label: "Klimawandel: Ursachen, Folgen, Maßnahmen" }, { id: "ressourcen", label: "Geopolitik & Ressourcen" }, { id: "disparitaeten", label: "Disparitäten: Global & Regional" }] },
      { grade: 13, topics: [{ id: "abitur-stadtgeo", label: "Abitur: Stadtgeografie" }, { id: "abitur-klima", label: "Abitur: Klimawandel & Nachhaltigkeit" }, { id: "abitur-globalisierung", label: "Abitur: Globalisierung & Entwicklung" }] },
    ]
  },
  {
    id: "politik", label: "Politik", color: "#FFF176",
    grades: [
      { grade: 5, topics: [{ id: "demokratie", label: "Was ist Demokratie?" }, { id: "schule-regeln", label: "Schule & Regeln" }, { id: "rechte-pflichten", label: "Meine Rechte & Pflichten" }] },
      { grade: 8, topics: [{ id: "pol-system", label: "Politisches System Deutschlands" }, { id: "marktwirtschaft", label: "Soziale Marktwirtschaft" }, { id: "medien-demokratie", label: "Medien & Demokratie" }] },
      { grade: 9, topics: [{ id: "menschenrechte", label: "Menschenrechte" }, { id: "internationale-org", label: "Internationale Organisationen" }, { id: "soziale-gerechtigkeit", label: "Soziale Gerechtigkeit" }] },
      { grade: 10, topics: [{ id: "eu", label: "Europäische Union" }, { id: "globale-heraus", label: "Globale Herausforderungen" }, { id: "wahlsysteme", label: "Wahlsysteme & Partizipation" }] },
      { grade: 11, topics: [{ id: "demokratietheorien", label: "Demokratietheorien" }, { id: "wirtschaftspolitik", label: "Wirtschaftspolitik & Konjunktur" }, { id: "sozialpolitik", label: "Sozialpolitik & Wohlfahrtsstaat" }] },
      { grade: 12, topics: [{ id: "sicherheitspolitik", label: "Internationale Beziehungen & Sicherheitspolitik" }, { id: "migration-integration", label: "Migration & Integration" }, { id: "medien-oeffentlichkeit", label: "Medien, Öffentlichkeit & Demokratie" }] },
      { grade: 13, topics: [{ id: "abitur-pol-system", label: "Abitur: Politisches System im Vergleich" }, { id: "abitur-int-politik", label: "Abitur: Internationale Politik" }, { id: "abitur-wirtschaft", label: "Abitur: Wirtschaft & soziale Ungleichheit" }] },
    ]
  },
  {
    id: "informatik", label: "Informatik", color: "#90CAF9",
    grades: [
      { grade: 5, topics: [{ id: "computer-basics", label: "Was ist ein Computer?" }, { id: "internet-sicher", label: "Sicheres Verhalten im Internet" }, { id: "textverarbeitung", label: "Grundlagen Textverarbeitung" }] },
      { grade: 7, topics: [{ id: "algorithmen", label: "Algorithmen & Programmieren Einführung" }, { id: "datenschutz", label: "Daten & Datenschutz" }, { id: "tabellen", label: "Tabellenkalkulation" }] },
      { grade: 8, topics: [{ id: "programmieren", label: "Programmieren: Schleifen & Bedingungen" }, { id: "netzwerke", label: "Netzwerke Grundlagen" }, { id: "datenbanken", label: "Datenbanken einfach" }] },
      { grade: 9, topics: [{ id: "oop", label: "Objektorientiertes Programmieren" }, { id: "ki-grundlagen", label: "Künstliche Intelligenz Grundlagen" }, { id: "cyber", label: "Cybersicherheit" }] },
      { grade: 10, topics: [{ id: "software-entw", label: "Softwareentwicklung" }, { id: "digitalisierung", label: "Gesellschaft & Digitalisierung" }, { id: "ki-ethik", label: "KI & Ethik" }] },
      { grade: 11, topics: [{ id: "automaten", label: "Automaten & formale Sprachen" }, { id: "rekursion", label: "Rekursion & Komplexität" }, { id: "datenstrukturen", label: "Datenstrukturen: Listen, Bäume, Graphen" }] },
      { grade: 12, topics: [{ id: "sql", label: "Datenbankdesign & SQL" }, { id: "kryptographie", label: "Kryptographie & Sicherheit" }, { id: "ml", label: "Maschinelles Lernen: Grundlagen & Anwendung" }] },
      { grade: 13, topics: [{ id: "abitur-oop", label: "Abitur: Objektorientierung & Modellierung" }, { id: "abitur-algo", label: "Abitur: Algorithmen & Datenstrukturen" }, { id: "abitur-db", label: "Abitur: Datenbanken" }, { id: "ki-gesellschaft", label: "KI, Ethik & gesellschaftliche Implikationen" }] },
    ]
  },
  { id: "musik", label: "Musik", color: "#CE93D8", grades: [{ grade: 5, topics: [{ id: "notenlehre", label: "Grundlagen der Notenlehre" }, { id: "rhythmus", label: "Rhythmus & Takt" }, { id: "instrumente", label: "Musikinstrumente" }] }, { grade: 6, topics: [{ id: "dur-moll", label: "Dur & Moll" }, { id: "andere-kulturen", label: "Musik aus anderen Kulturen" }, { id: "komposition", label: "Komposition einfach" }] }, { grade: 7, topics: [{ id: "barock-klassik", label: "Musikgeschichte: Barock & Klassik" }, { id: "gehoerbildung", label: "Gehörbildung vertieft" }, { id: "liedanalyse", label: "Liedanalyse" }] }, { grade: 8, topics: [{ id: "romantik", label: "Romantik & Impressionismus" }, { id: "jazz", label: "Jazz & Blues" }, { id: "filmmusik", label: "Filmmusik" }] }, { grade: 9, topics: [{ id: "neue-musik", label: "20. Jahrhundert: Neue Musik" }, { id: "pop-rock", label: "Pop & Rock Analyse" }, { id: "musik-gesellschaft", label: "Musik & Gesellschaft" }] }, { grade: 10, topics: [{ id: "musikproduktion", label: "Musikproduktion Grundlagen" }, { id: "zeitgenoessisch", label: "Zeitgenössische Musik" }, { id: "identitaet", label: "Musik & Identität" }] }, { grade: 11, topics: [{ id: "analyse-vertieft", label: "Musikalische Analyse vertieft" }, { id: "sonatenform", label: "Sonatenform & symphonische Musik" }, { id: "avantgarde", label: "Musik des 20. Jh.: Avantgarde & Minimalismus" }] }, { grade: 12, topics: [{ id: "oper", label: "Oper & Musiktheater" }, { id: "elektronik", label: "Elektronische Musik & Klanggestaltung" }, { id: "lied", label: "Musik & Sprache: Lied & Chanson" }] }, { grade: 13, topics: [{ id: "abitur-werk", label: "Abitur: Werkanalyse" }, { id: "abitur-kontext", label: "Abitur: Musik & Kontext" }, { id: "komposition-abi", label: "Kompositorisches Gestalten" }] }] },
  { id: "kunst", label: "Kunst", color: "#F48FB1", grades: [{ grade: 5, topics: [{ id: "farblehre", label: "Farblehre Grundlagen" }, { id: "zeichnen", label: "Zeichnen & Beobachten" }, { id: "plastisch", label: "Plastisches Gestalten" }] }, { grade: 6, topics: [{ id: "perspektive", label: "Perspektive Einführung" }, { id: "kunstbetrachtung", label: "Kunstbetrachtung: Gemälde lesen" }, { id: "drucktechniken", label: "Drucktechniken" }] }, { grade: 7, topics: [{ id: "stilrichtungen", label: "Stilrichtungen: Realismus & Abstraktion" }, { id: "portraet", label: "Porträt & Figur" }, { id: "collage", label: "Collage & Mixed Media" }] }, { grade: 8, topics: [{ id: "expressionismus", label: "Moderne Kunst: Expressionismus" }, { id: "fotografie", label: "Fotografie als Kunst" }, { id: "architektur", label: "Architektur & Design" }] }, { grade: 9, topics: [{ id: "zeitgenoessisch-kunst", label: "Zeitgenössische Kunst" }, { id: "medienkunst", label: "Medienkunst" }, { id: "konzeptkunst", label: "Konzeptkunst & Installation" }] }, { grade: 10, topics: [{ id: "kunstanalyse", label: "Kunstanalyse vertieft" }, { id: "haltung", label: "Eigene künstlerische Haltung" }, { id: "kunst-gesellschaft", label: "Kunst & Gesellschaft" }] }, { grade: 11, topics: [{ id: "bildanalyse", label: "Bildanalyse & Interpretation vertieft" }, { id: "kubismus", label: "Kunst der Moderne: Kubismus bis Surrealismus" }, { id: "kuenstlerische-arbeit", label: "Eigene künstlerische Arbeit: Konzept & Umsetzung" }] }, { grade: 12, topics: [{ id: "pop-art", label: "Kunst nach 1945: Pop Art, Minimalismus, Konzeptkunst" }, { id: "bild-text", label: "Bild & Text – intermediale Bezüge" }, { id: "ausstellung", label: "Ausstellungs- & Präsentationskonzepte" }] }, { grade: 13, topics: [{ id: "abitur-bildanalyse", label: "Abitur: Bildanalyse" }, { id: "abitur-vergleich", label: "Abitur: Vergleich zweier Werke" }, { id: "pruefungsarbeit", label: "Künstlerische Prüfungsarbeit" }] }] },
  { id: "sport", label: "Sport", color: "#80DEEA", grades: [{ grade: 5, topics: [{ id: "bewegung", label: "Bewegungsgrundlagen" }, { id: "leichtathletik", label: "Leichtathletik Einführung" }, { id: "ballsport", label: "Ballsportarten" }] }, { grade: 6, topics: [{ id: "schwimmen", label: "Schwimmen & Wassersicherheit" }, { id: "turnen", label: "Turnen an Geräten" }, { id: "spielkonzepte", label: "Spielkonzepte" }] }, { grade: 7, topics: [{ id: "ausdauer", label: "Kondition & Ausdauer" }, { id: "taktik", label: "Taktik in Mannschaftsspielen" }, { id: "fitness", label: "Fitness & Gesundheit" }] }, { grade: 8, topics: [{ id: "trainingslehre", label: "Trainingslehre Grundlagen" }, { id: "biomechanik", label: "Sporttheorie & Biomechanik" }, { id: "kampfsport", label: "Kampfsport" }] }, { grade: 9, topics: [{ id: "sportpsychologie", label: "Sportpsychologie" }, { id: "ernaehrung", label: "Ernährung & Sport" }, { id: "fairplay", label: "Wettkampf & Fair Play" }] }, { grade: 10, topics: [{ id: "sportmedizin", label: "Sportmedizin Grundlagen" }, { id: "leistungssport", label: "Leistungssport & Gesellschaft" }, { id: "wohlbefinden", label: "Bewegung & Wohlbefinden" }] }, { grade: 11, topics: [{ id: "periodisierung", label: "Trainingsplanung & Periodisierung" }, { id: "bewegungslehre", label: "Bewegungslehre vertieft" }, { id: "praevention", label: "Sport & Gesundheit: Prävention" }] }, { grade: 12, topics: [{ id: "doping", label: "Sport & Gesellschaft: Doping, Kommerz, Medien" }, { id: "sportpaedagogik", label: "Sportpädagogik & Erziehung" }, { id: "biomechanik-os", label: "Biomechanische Analyse" }] }, { grade: 13, topics: [{ id: "abitur-theorie", label: "Abitur: Sporttheorie" }, { id: "abitur-training", label: "Abitur: Trainingslehre" }, { id: "sport-ethik", label: "Sport & ethische Fragestellungen" }] }] },
  { id: "religion", label: "Religion", color: "#F9E79F", grades: [{ grade: 5, topics: [{ id: "glaube", label: "Was ist Glauben?" }, { id: "weltreligionen", label: "Weltreligionen im Überblick" }, { id: "schoepfung", label: "Schöpfungsgeschichten" }] }, { grade: 6, topics: [{ id: "jesus", label: "Jesus von Nazareth" }, { id: "judentum", label: "Judentum & Christentum" }, { id: "ethik-alltag", label: "Ethische Fragen im Alltag" }] }, { grade: 7, topics: [{ id: "islam", label: "Islam Grundlagen" }, { id: "buddhismus", label: "Buddhismus & Hinduismus" }, { id: "gerechtigkeit", label: "Gerechtigkeit & Menschenwürde" }] }, { grade: 8, topics: [{ id: "bibel", label: "Bibel lesen & verstehen" }, { id: "kirche-geschichte", label: "Kirche in der Geschichte" }, { id: "tod", label: "Sterben & Tod" }] }, { grade: 9, topics: [{ id: "theodizee", label: "Theodizee-Frage" }, { id: "extremismus", label: "Religiöser Extremismus" }, { id: "glaube-wissenschaft", label: "Glaube & Wissenschaft" }] }, { grade: 10, topics: [{ id: "ethik-modern", label: "Ethik & moderne Gesellschaft" }, { id: "oekumene", label: "Ökumene & interreligiöser Dialog" }, { id: "spiritualitaet", label: "Sinn & Spiritualität" }] }, { grade: 11, topics: [{ id: "gottesbilder", label: "Gottesbilder im Vergleich" }, { id: "religionskritik", label: "Religionskritik: Feuerbach, Marx, Nietzsche" }, { id: "eschatologie", label: "Eschatologie & Jenseitsglaube" }] }, { grade: 12, topics: [{ id: "bioethik", label: "Ethische Grundfragen: Bioethik, KI, Umwelt" }, { id: "mystik", label: "Mystik & spirituelle Erfahrung" }, { id: "religionen-gewalt", label: "Religionen & Gewalt" }] }, { grade: 13, topics: [{ id: "abitur-gott", label: "Abitur: Gottesvorstellungen" }, { id: "abitur-ethik", label: "Abitur: Ethische Urteilsbildung" }, { id: "abitur-religion-gesellschaft", label: "Abitur: Religion & Gesellschaft" }] }] },
  { id: "wirtschaft", label: "Wirtschaft", color: "#B3E5FC", grades: [{ grade: 8, topics: [{ id: "haushalte", label: "Haushalte & Budgets" }, { id: "maerkte", label: "Märkte & Preise" }, { id: "unternehmen", label: "Unternehmen & Produktion" }] }, { grade: 9, topics: [{ id: "arbeitsmarkt", label: "Arbeitsmarkt & Berufsplanung" }, { id: "banken", label: "Geld & Banken" }, { id: "soziale-sicherung", label: "Soziale Sicherung" }] }, { grade: 10, topics: [{ id: "globalisierung-w", label: "Globalisierung & Wirtschaft" }, { id: "konjunktur", label: "Konjunktur & Wirtschaftspolitik" }, { id: "nachhaltigkeit-w", label: "Nachhaltigkeit & Wirtschaft" }] }, { grade: 11, topics: [{ id: "unternehmensorg", label: "Unternehmensorganisation & Rechtsformen" }, { id: "mikro-makro", label: "Mikro- & Makroökonomie Einführung" }, { id: "finanzierung", label: "Finanzierung & Investition" }] }, { grade: 12, topics: [{ id: "wirtschaftspolitik-os", label: "Wirtschaftspolitik vertieft" }, { id: "internationale-wirtschaft", label: "Internationale Wirtschaftsbeziehungen" }, { id: "csr", label: "Wirtschaftsethik & CSR" }] }, { grade: 13, topics: [{ id: "abitur-markt", label: "Abitur: Markt & Wettbewerb" }, { id: "abitur-konjunktur", label: "Abitur: Konjunktur & Wachstum" }, { id: "abitur-marktwirtschaft", label: "Abitur: Soziale Marktwirtschaft" }] }] },
  { id: "franzoesisch", label: "Französisch", color: "#FFAB91", grades: [{ grade: 6, topics: [{ id: "se-presenter", label: "Se présenter" }, { id: "famille", label: "La famille" }, { id: "couleurs", label: "Les couleurs & les chiffres" }] }, { grade: 7, topics: [{ id: "present", label: "Le présent" }, { id: "vie-quotidienne", label: "La vie quotidienne" }, { id: "personnes", label: "Décrire des personnes" }] }, { grade: 8, topics: [{ id: "passe-compose", label: "Le passé composé" }, { id: "ville", label: "La ville & les directions" }, { id: "medias", label: "Les médias" }] }, { grade: 9, topics: [{ id: "subjonctif", label: "Le subjonctif Einführung" }, { id: "francophonie", label: "La France & la francophonie" }, { id: "argumenter", label: "Argumenter en français" }] }, { grade: 10, topics: [{ id: "analyse-texte", label: "Analyse de textes" }, { id: "debats", label: "Débats actuels" }, { id: "litterature", label: "Littérature française" }] }, { grade: 11, topics: [{ id: "roman", label: "Littérature francophone: roman & nouvelle" }, { id: "societe", label: "Société française contemporaine" }, { id: "commentaire", label: "Écriture analytique & commentaire" }] }, { grade: 12, topics: [{ id: "cinema", label: "Cinéma & culture française" }, { id: "europe", label: "La France & l'Europe" }, { id: "litterature-20", label: "Textes littéraires du 20e siècle" }] }, { grade: 13, topics: [{ id: "abitur-analyse", label: "Abitur: Analyse de texte" }, { id: "abitur-mediation", label: "Abitur: Médiation" }, { id: "abitur-expression", label: "Abitur: Expression écrite" }] }] },
  { id: "latein", label: "Latein", color: "#CFD8DC", grades: [{ grade: 6, topics: [{ id: "vokabular", label: "Grundvokabular & Aussprache" }, { id: "nom-akk", label: "Nominativ & Akkusativ" }, { id: "erste-saetze", label: "Erste Sätze übersetzen" }] }, { grade: 7, topics: [{ id: "deklinationen", label: "Deklinationen" }, { id: "konjugationen", label: "Konjugationen Präsens" }, { id: "alltagskultur", label: "Römische Alltagskultur" }] }, { grade: 8, topics: [{ id: "ablativ", label: "Ablativ & weitere Kasus" }, { id: "participium", label: "Participium" }, { id: "roemische-geschichte", label: "Römische Geschichte" }] }, { grade: 9, topics: [{ id: "konjunktiv", label: "Konjunktiv" }, { id: "uebersetzung", label: "Übersetzungstexte vertieft" }, { id: "rhetorik", label: "Philosophie & Rhetorik" }] }, { grade: 10, topics: [{ id: "caesar", label: "Originaltexte: Caesar" }, { id: "cicero-intro", label: "Cicero Einführung" }, { id: "antike-moderne", label: "Antike & Moderne" }] }, { grade: 11, topics: [{ id: "cicero-os", label: "Cicero: De re publica / De officiis" }, { id: "ovid", label: "Ovid: Metamorphosen" }, { id: "stilmittel", label: "Stilmittel & Übersetzungsmethodik" }] }, { grade: 12, topics: [{ id: "vergil", label: "Vergil: Aeneis" }, { id: "tacitus", label: "Tacitus: Annalen" }, { id: "geistesgeschichte", label: "Latein & Europäische Geistesgeschichte" }] }, { grade: 13, topics: [{ id: "abitur-uebersetzung", label: "Abitur: Übersetzung & Interpretation" }, { id: "abitur-antike", label: "Abitur: Vergleich Antike–Rezeption" }, { id: "philosophie-antike", label: "Philosophie & Lebensentwürfe in der Antike" }] }] },
];

export const getSubject = (id: string) => SUBJECTS.find(s => s.id === id);
export const getSubjectColor = (id: string) => getSubject(id)?.color ?? "#7EC8E3";
export const getGradesForSubject = (id: string) => getSubject(id)?.grades.map(g => g.grade) ?? [];
export const getTopicsForGrade = (subjectId: string, grade: number) =>
  getSubject(subjectId)?.grades.find(g => g.grade === grade)?.topics ?? [];
